### ISSUE TITLE
Question on the difference between CAROIPooling and CAROIPooling2

### ISSUE THREAD

**Issue by e2sh83** [xw-hu/SINet#3]
Hi xw-hu,

First, I am wondering where you utilize CAROIPooling2 layer in your source code.
Second, CAROIPooling2 seems to have function of both CAROIPooling and ROIFeatureSplit. Do I correctly understand?

**Comment by xw-hu** [comment]
Yes. You are correct. We use CAROIPooling2 in the old version. 
Now, we only use the CAROIPooling  and ROIFeatureSplit, since they are easy to be extended to multiple branches.

**Comment by e2sh83** [comment]
Thank you for answer. 
Another question which is not related to the title of this thread is... have you tried to apply your algorithm onto the other classes like pedestrian?

**Comment by xw-hu** [comment]
No. I think it will also give a relative good result for pedestrian by adjusting some parameters (e.g., the size of anchor). You can try it.

**Comment by e2sh83** [comment]
Thanks a lot.
